"use client";

import React, { useEffect, useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import RoadmapTimeline from "@/components/RoadmapTimeline";
import ReasoningTrace from "@/components/ReasoningTrace";
import SkillGapChart from "@/components/SkillGapChart";
import MatchScoreRing from "@/components/MatchScoreRing";
import WeeklyTimeline from "@/components/WeeklyTimeline";
import SkillGraph from "@/components/SkillGraph";
import AnimatedCounter from "@/components/AnimatedCounter";
import { Download, Book, Clock, Zap, Target, Share2, X, Check } from "lucide-react";
import confetti from "canvas-confetti";
import axios from "axios";
import SKILL_DEMAND from "@/data/skillDemand";

interface RoadmapData {
  session_id?: string;
  match_score: number;
  skill_gaps: { skill: string; gap_relevance?: number; gap_score?: number }[];
  resume_skills?: { skill: string; level?: string }[];
  reasoning_trace?: string;
  pathway: {
    pathway: any[];
    total_courses: number;
    total_estimated_hours: number;
    courses_skipped: number;
  };
}

function RoadmapContent() {
  const [data, setData] = useState<RoadmapData | null>(null);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<"timeline" | "weekly">("timeline");
  const [completedCount, setCompletedCount] = useState(0);
  const [toastMessage, setToastMessage] = useState("");
  const [showCertificate, setShowCertificate] = useState(false);
  const [copied, setCopied] = useState(false);
  const router = useRouter();
  const searchParams = useSearchParams();
  const sessionId = searchParams.get("session");

  useEffect(() => {
    const minDelay = new Promise(resolve => setTimeout(resolve, 800));
    
    const loadData = async () => {
      try {
        if (sessionId) {
          // If we had an API endpoint: 
          // const res = await axios.get(`/api/pathway/session/${sessionId}`);
          // setData(res.data);
          // For now rely on localstorage if we're simulating the session without full backend support
          // If it's stored under another API we could fetch it.
        }
        
        const raw = localStorage.getItem("pathway_data");
        if (raw) {
          const parsed = JSON.parse(raw);
          setData(parsed);
          
          if (parsed.session_id && !sessionId) {
            window.history.replaceState({}, "", `/roadmap?session=${parsed.session_id}`);
          }

          if (parsed?.pathway?.pathway?.length > 0) {
            setTimeout(() => {
              confetti({
                particleCount: 80,
                spread: 60,
                origin: { y: 0.6 },
                colors: ["#4F9EF8", "#7C3AED", "#10B981", "#F59E0B"]
              });
            }, 600);
          }
        }
      } catch (err) {
        console.error("Failed to load pathway_data", err);
      }
    };

    Promise.all([loadData(), minDelay]).then(() => {
      setLoading(false);
    });
  }, [sessionId]);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(""), 3000);
  };

  useEffect(() => {
    if (data && data.pathway.pathway.length > 0 && completedCount === data.pathway.pathway.length) {
      setTimeout(() => setShowCertificate(true), 500);
    }
  }, [completedCount, data]);

  useEffect(() => {
    if (showCertificate) {
      confetti({ particleCount: 150, spread: 100, colors: ["#4F9EF8", "#7C3AED", "#10B981", "#F59E0B"] });
    }
  }, [showCertificate]);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT") return;
      if (e.key === "Escape") router.push("/");
      if (e.key === "e" || e.key === "E") handleExport();
      if (e.key === "c" || e.key === "C") copyPathway();
      if (e.key === "h" || e.key === "H") router.push("/history");
      if (e.key === "r" || e.key === "R") {
        document.querySelector("[data-reasoning]")?.scrollIntoView({ behavior: "smooth" });
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  });

  const handleDownloadCertificate = () => {
    if (!data) return;
    const lines = [
      "===========================",
      "CERTIFICATE OF COMPLETION",
      "===========================",
      "Awarded for completing the personalized",
      "learning pathway for your target role",
      "",
      `Courses completed: ${data.pathway.pathway.length}`,
      `Total learning hours: ${data.pathway.total_estimated_hours}h`,
      `Role match score: ${Math.round(data.match_score * 100)}%`,
      "",
      "Generated by AI-Adaptive Onboarding Engine",
      `Date: ${new Date().toLocaleDateString()}`,
      "===========================",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "certificate.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShareAchievement = () => {
    navigator.clipboard.writeText(window.location.href);
    showToast("Achievement link copied! \u2713");
  };

  const handleShare = () => {
    const shareUrl = window.location.href;
    navigator.clipboard.writeText(shareUrl);
    showToast("Link copied to clipboard! ✓");
  };

  const copyPathway = () => {
    if (!data) return;
    const courses = data.pathway.pathway;
    const text = [
      `Match Score: ${Math.round(data.match_score * 100)}%`,
      `Courses: ${courses.length} | Hours: ${data.pathway.total_estimated_hours}h | Skipped: ${data.pathway.courses_skipped}`,
      "",
      "Skill Gaps:",
      ...data.skill_gaps.map((g: any) => `- ${g.skill || g.catalog_skill}`),
      "",
      "Pathway:",
      ...courses.map((c: any, i: number) => `${i + 1}. ${c.display_name} (${c.estimated_hours}h)`),
    ].join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    if (!data) return;

    const courses = data.pathway.pathway;
    const lines = [
      "=== MY PERSONALIZED LEARNING PATHWAY ===",
      `Generated: ${new Date().toLocaleDateString()}`,
      "",
      "=== SUMMARY ===",
      `Total Courses: ${courses.length}`,
      `Total Hours: ${data.pathway.total_estimated_hours}h`,
      `Courses Skipped: ${data.pathway.courses_skipped} (already in your skillset)`,
      `Role Match Score: ${Math.round(data.match_score * 100)}%`,
      "",
      "=== IDENTIFIED SKILL GAPS ===",
      ...data.skill_gaps.map((g: any) => `- ${g.skill || g.catalog_skill}`),
      "",
      "=== YOUR LEARNING PATHWAY ===",
      ...courses.map((c: any, i: number) => [
        `${i+1}. ${c.display_name}`,
        `   Category: ${c.category} | Level: ${c.level} | Time: ${c.estimated_hours}h`,
        `   ${c.description}`,
        c.resources?.length > 0 
          ? `   Resources: ${c.resources.map((r: any) => r.name + " - " + r.url).join(", ")}`
          : "",
        ""
      ].join("\n")),
      "=== AI REASONING ===",
      data.reasoning_trace || "No reasoning available",
      "",
      "Generated by AI-Adaptive Onboarding Engine"
    ].join("\n");

    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "my-learning-pathway.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#060810] py-12 px-6">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="h-10 bg-[var(--bg-elevated)] rounded w-1/3 animate-pulse mb-6"></div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
            {[...Array(4)].map((_, i) => (
              <div key={i} className="h-28 bg-[var(--bg-surface)] rounded-xl animate-pulse"></div>
            ))}
          </div>
          <div className="flex gap-8">
            <div className="flex-1 flex flex-col gap-6">
              {[...Array(4)].map((_, i) => (
                <div key={i} className="bg-[var(--bg-surface)] rounded-xl p-4 flex gap-4 animate-pulse">
                  <div className="w-12 h-12 bg-[var(--bg-elevated)] rounded-full flex-shrink-0"></div>
                  <div className="flex-1">
                    <div className="h-4 bg-[var(--bg-elevated)] rounded w-3/4 mb-3"></div>
                    <div className="flex gap-2 mb-3">
                      <div className="h-5 w-16 bg-[var(--bg-elevated)] rounded-full"></div>
                      <div className="h-5 w-16 bg-[var(--bg-elevated)] rounded-full"></div>
                      <div className="h-5 w-16 bg-[var(--bg-elevated)] rounded-full"></div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="hidden lg:block w-80 h-96 bg-[var(--bg-surface)] rounded-xl animate-pulse"></div>
          </div>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="min-h-screen bg-[#060810] flex flex-col items-center justify-center text-[var(--text-primary)] p-6 text-center">
        <h2 className="text-2xl font-[var(--font-syne)] font-bold mb-3">No analysis data found</h2>
        <p className="text-[var(--text-secondary)] mb-6">
          Please upload your resume and job description first to generate a pathway.
        </p>
        <a
          href="/"
          className="px-6 py-3 bg-gradient-to-r from-[#4F9EF8] to-[#7C3AED] hover:from-[#4F9EF8]/90 hover:to-[#7C3AED]/90 transition-all rounded-xl font-[var(--font-syne)] font-bold"
        >
          Go to Home
        </a>
      </div>
    );
  }

  const matchPercent = Math.round(data.match_score * 100);
  const isAboveAvg = matchPercent > 42;
  const savedModules = 40 - data.pathway.total_courses;
  const savedHours = 400 - data.pathway.total_estimated_hours;
  const totalHours = data.pathway.total_estimated_hours;
  const weeksNeeded = Math.ceil(totalHours / 10);
  const completionDate = new Date();
  completionDate.setDate(completionDate.getDate() + (weeksNeeded * 7));
  const completionMonth = completionDate.toLocaleString("default", {
    month: "long",
    year: "numeric"
  });

  return (
    <div className="min-h-screen bg-[#060810] text-[var(--text-primary)] font-[var(--font-dm-sans)] py-12 px-6 tracking-wide relative overflow-hidden">
      {/* Ambient Glow Orbs */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -left-40 w-[500px] h-[500px] rounded-full bg-[#4F9EF8]/[0.06] blur-[120px]" />
        <div className="absolute -bottom-40 -right-40 w-[500px] h-[500px] rounded-full bg-[#7C3AED]/[0.06] blur-[120px]" />
      </div>
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 bg-[#10B981]/90 text-white px-5 py-3 rounded-xl shadow-lg animate-slide-in-right backdrop-blur-sm">
          {toastMessage}
        </div>
      )}

      <div className="max-w-6xl mx-auto relative z-10">
        <div className="mb-8 flex flex-col sm:flex-row sm:items-center justify-between gap-4 fade-up">
          <div>
            <h1 className="text-3xl font-[var(--font-syne)] font-extrabold mb-2 gradient-text">Your Learning Pathway</h1>
            <p className="text-[var(--text-secondary)] text-sm">
              Personalized roadmap generated by AI based on your resume and job description
            </p>
          </div>
          <div className="flex gap-2 flex-wrap no-print">
            <button
              onClick={() => router.push("/history")}
              className="card-premium text-sm px-4 py-2 hover:border-[#4F9EF8]/30 transition-all"
            >
              History
            </button>
            <button
              onClick={handleShare}
              className="card-premium text-sm px-4 py-2 flex items-center gap-2 hover:border-[#4F9EF8]/30 transition-all"
            >
              <Share2 size={16} /> Share
            </button>
            <button
              onClick={handleExport}
              className="bg-gradient-to-r from-[#4F9EF8] to-[#7C3AED] hover:from-[#4F9EF8]/90 hover:to-[#7C3AED]/90 text-white text-sm px-4 py-2 rounded-2xl flex items-center gap-2 transition-all shadow-lg"
            >
              <Download size={16} /> Export Pathway
            </button>
            <button
              onClick={copyPathway}
              className="card-premium text-sm px-4 py-2 flex items-center gap-2 hover:border-[#10B981]/30 transition-all"
            >
              {copied ? <><Check size={16} className="text-[#10B981]" /> Copied! ✓</> : <><Share2 size={16} /> Copy Pathway</>}
            </button>
            <button
              onClick={() => window.print()}
              className="card-premium text-sm px-3 py-1.5 hover:border-[#4F9EF8]/30 transition-all"
            >
              Print
            </button>
          </div>
        </div>

        {/* Before vs After Banner */}
        <div className="w-full card-premium bg-gradient-to-r from-[var(--bg-surface)] to-[var(--bg-elevated)] p-6 mb-8 fade-up fade-up-delay-1">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6 pb-6">
            <div className="flex-1 flex flex-col items-center">
              <span className="text-red-400 font-[var(--font-syne)] font-bold mb-3">WITHOUT AI Onboarding</span>
              <div className="space-y-2 text-sm text-[var(--text-secondary)]">
                <p className="flex items-center gap-2 justify-end"><X size={16} className="text-red-400"/> 40 modules</p>
                <p className="flex items-center gap-2 justify-end"><X size={16} className="text-red-400"/> 400 hours</p>
                <p className="flex items-center gap-2 justify-end"><X size={16} className="text-red-400"/> Generic for everyone</p>
              </div>
            </div>
            
            <div className="bg-gradient-to-br from-[#4F9EF8] to-[#7C3AED] text-white rounded-full w-12 h-12 flex items-center justify-center font-[var(--font-syne)] font-bold text-lg flex-shrink-0 shadow-lg shadow-[#4F9EF8]/30">
              VS
            </div>

            <div className="flex-1 flex flex-col items-center">
              <span className="text-[#10B981] font-[var(--font-syne)] font-bold mb-3">WITH AI Adaptive Onboarding</span>
              <div className="space-y-2 text-sm text-[var(--text-secondary)]">
                <p className="flex items-center gap-2"><Check size={16} className="text-[#10B981]"/> {data.pathway.total_courses} modules</p>
                <p className="flex items-center gap-2"><Check size={16} className="text-[#10B981]"/> {data.pathway.total_estimated_hours} hours</p>
                <p className="flex items-center gap-2"><Check size={16} className="text-[#10B981]"/> Personalized for YOU</p>
              </div>
            </div>
          </div>
          
          <div className="w-full bg-[#4F9EF8]/10 rounded-xl p-3 mt-2 text-center border border-[#4F9EF8]/20">
            <p className="text-[#4F9EF8] font-[var(--font-syne)] font-bold">
              🎉 You save approximately {savedModules > 0 ? savedModules : 0} modules and {savedHours > 0 ? savedHours : 0} hours compared to generic onboarding
            </p>
          </div>
        </div>

        {/* Skill Gap Chart */}
        {data.skill_gaps && data.skill_gaps.length > 0 && (
          <div className="mb-8 w-full">
            <SkillGapChart scoreMap={Object.fromEntries(
              data.skill_gaps.map(g => [g.skill, g.gap_relevance ?? g.gap_score ?? 0.5])
            )} />
          </div>
        )}

        {/* Skill Graph */}
        {data.skill_gaps && data.skill_gaps.length > 0 && (
          <div className="w-full mb-6 fade-up fade-up-delay-2">
            <SkillGraph
              resumeSkills={(data as any).resume_skills || data.skill_gaps.filter(g => (g.gap_relevance ?? g.gap_score ?? 0.5) < 0.3).map(g => ({ skill: g.skill, level: "known" }))}
              jdSkills={data.skill_gaps.map(g => ({ skill: g.skill, priority: (g.gap_relevance ?? g.gap_score ?? 0.5) > 0.7 ? "high" : "medium" }))}
              gaps={data.skill_gaps.map(g => ({ skill: g.skill, gap_severity: g.gap_relevance ?? g.gap_score ?? 0.5 }))}
            />
          </div>
        )}

        {/* Skill Gap Chips with Market Demand */}
        {data.skill_gaps && data.skill_gaps.length > 0 && (
          <div className="mb-8 fade-up fade-up-delay-2">
            <h3 className="text-sm font-[var(--font-syne)] font-bold text-[var(--text-secondary)] mb-3 uppercase tracking-wider">Identified Skill Gaps</h3>
            <div className="flex flex-wrap gap-2">
              {data.skill_gaps.map((gap: any, i: number) => {
                const skillName = gap.skill || gap.catalog_skill;
                const demand = SKILL_DEMAND[skillName];
                return (
                  <div key={i} className="group relative">
                    <span className="text-xs px-3 py-1.5 rounded-full bg-[rgba(239,68,68,0.08)] text-[#EF4444] border border-[rgba(239,68,68,0.15)] flex items-center gap-2 cursor-pointer">
                      {skillName}
                      {demand && (
                        <span className={`text-[10px] px-1.5 py-0.5 rounded-full ${
                          demand.level === "hot"
                            ? "bg-[rgba(239,68,68,0.15)] text-[#EF4444]"
                            : demand.level === "high"
                            ? "bg-[rgba(79,158,248,0.15)] text-[#4F9EF8]"
                            : "bg-[rgba(16,185,129,0.15)] text-[#10B981]"
                        }`}>
                          {demand.label}
                        </span>
                      )}
                    </span>
                    {demand && (
                      <div className="absolute bottom-full left-0 mb-2 z-20 bg-[#0D1117] border border-[rgba(255,255,255,0.1)] rounded-lg px-3 py-2 text-[11px] text-white opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap">
                        Market demand: {demand.trend}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Stats Bar */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-10 fade-up fade-up-delay-2">
          <div className="card-premium p-5">
            <div className="flex items-center gap-2 mb-2 text-[var(--text-muted)] text-xs">
              <Book size={14} /> Total Courses
            </div>
            <p className="stat-number text-3xl text-[#4F9EF8] mb-1"><AnimatedCounter value={data.pathway.total_courses} /></p>
            <p className="text-[10px] text-[var(--text-muted)] uppercase tracking-wider">in your pathway</p>
          </div>
          
          <div className="card-premium p-5">
            <div className="flex items-center gap-2 mb-2 text-[var(--text-muted)] text-xs">
              <Clock size={14} /> Total Hours
            </div>
            <p className="stat-number text-3xl text-[#F59E0B] mb-1"><AnimatedCounter value={data.pathway.total_estimated_hours} suffix="h" /></p>
            <p className="text-[10px] text-[var(--text-muted)] uppercase tracking-wider">estimated</p>
          </div>
          
          <div className="card-premium p-5">
            <div className="flex items-center gap-2 mb-2 text-[var(--text-muted)] text-xs">
              <Zap size={14} /> Courses Skipped
            </div>
            <p className="stat-number text-3xl text-[#10B981] mb-1"><AnimatedCounter value={data.pathway.courses_skipped} /></p>
            <p className="text-[10px] text-[var(--text-muted)] uppercase tracking-wider">already mastered</p>
          </div>
          
          <div className="card-premium p-5 flex items-center justify-between relative overflow-hidden">
            <div>
              <div className="flex items-center gap-2 text-[var(--text-muted)] text-xs mb-3">
                <Target size={14} /> Role Match
              </div>
              {isAboveAvg ? (
                <span className="bg-[#10B981]/10 border border-[#10B981]/20 text-[#10B981] text-xs px-2 py-1 rounded-full flex items-center gap-1 w-max">
                  ↑ Above Avg
                </span>
              ) : (
                <span className="bg-[#F59E0B]/10 border border-[#F59E0B]/20 text-[#F59E0B] text-xs px-2 py-1 rounded-full flex items-center gap-1 w-max">
                  ↓ Below Avg
                </span>
              )}
              <p className="text-[10px] text-[var(--text-muted)] mt-2">vs 42% avg candidate</p>
            </div>
            <div className="w-16 h-16 ml-auto">
              <MatchScoreRing score={matchPercent} size={64} />
            </div>
          </div>
        </div>

        {/* Job-Ready Estimate Banner */}
        <div className="flex items-center justify-center gap-3 bg-[rgba(16,185,129,0.06)] border border-[rgba(16,185,129,0.12)] rounded-xl px-6 py-3 mb-6 fade-up fade-up-3">
          <span className="text-lg">🎯</span>
          <p className="text-sm text-[var(--text-secondary)]">
            At{" "}
            <span className="text-white font-medium">10 hours/week</span>
            {" "}you can be job-ready by{" "}
            <span className="text-[#10B981] font-semibold" style={{ fontFamily: "var(--font-syne)" }}>
              {completionMonth}
            </span>
          </p>
          <span className="text-xs text-[var(--text-muted)]">
            ({weeksNeeded} weeks)
          </span>
        </div>

        {/* View Toggles */}
        <div className="flex gap-4 mb-6 fade-up fade-up-delay-3">
          <button
            onClick={() => setViewMode("timeline")}
            className={`px-4 py-2 text-sm rounded-2xl border transition-all ${
              viewMode === "timeline" ? "bg-gradient-to-r from-[#4F9EF8] to-[#7C3AED] text-white border-transparent" : "card-premium text-[var(--text-secondary)] hover:text-white"
            }`}
          >
            Timeline View
          </button>
          <button
            onClick={() => setViewMode("weekly")}
            className={`px-4 py-2 text-sm rounded-2xl border transition-all ${
              viewMode === "weekly" ? "bg-gradient-to-r from-[#4F9EF8] to-[#7C3AED] text-white border-transparent" : "card-premium text-[var(--text-secondary)] hover:text-white"
            }`}
          >
            Weekly View
          </button>
        </div>

        {/* Skills You Already Have */}
        {data?.resume_skills && data.resume_skills.length > 0 && (
          <div className="card-premium p-5 mb-6 fade-up fade-up-3">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-sm font-semibold text-[var(--text-primary)]"
                  style={{ fontFamily: "var(--font-syne)" }}>
                  ✓ Skills You Already Have
                </h3>
                <p className="text-xs text-[var(--text-muted)] mt-0.5">
                  These courses were skipped from your pathway
                </p>
              </div>
              <span className="text-xs bg-[rgba(16,185,129,0.1)] text-[#10B981] border border-[rgba(16,185,129,0.2)] px-2 py-1 rounded-full">
                {data.resume_skills.length} skills
              </span>
            </div>
            <div className="flex flex-wrap gap-2">
              {data.resume_skills.map((skill: any, i: number) => (
                <span key={i}
                  className="flex items-center gap-1.5 text-xs bg-[rgba(16,185,129,0.06)] text-[#10B981] border border-[rgba(16,185,129,0.12)] px-3 py-1.5 rounded-full">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#10B981]" />
                  {skill.skill}
                  {skill.level && (
                    <span className="text-[#10B981]/60 text-[10px]">
                      {skill.level}
                    </span>
                  )}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Main Content */}
        <div className="flex flex-col lg:flex-row gap-8 relative">
          <div className="flex-1">
            {viewMode === "timeline" ? (
              <RoadmapTimeline 
                courses={data.pathway.pathway} 
                onCompletionChange={(count, total) => setCompletedCount(count)}
              />
            ) : (
              <WeeklyTimeline courses={data.pathway.pathway} hoursPerWeek={10} />
            )}
          </div>

          {data.reasoning_trace && (
            <div className="w-full lg:w-80 no-print" data-reasoning>
              <ReasoningTrace trace={data.reasoning_trace} />
            </div>
          )}
        </div>
      </div>
      {/* Certificate Modal */}
      {showCertificate && data && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center">
          <div
            className="bg-[#0D1117] border border-[rgba(79,158,248,0.2)] rounded-2xl p-10 max-w-lg w-full mx-4 text-center relative"
            style={{ boxShadow: "0 0 60px rgba(79,158,248,0.2)" }}
          >
            {/* Close button */}
            <button
              onClick={() => setShowCertificate(false)}
              className="absolute top-4 right-4 text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors text-xl leading-none"
            >
              &times;
            </button>

            {/* Gold star */}
            <div className="flex justify-center">
              <svg
                className="w-12 h-12"
                style={{ animation: "spin 8s linear infinite" }}
                viewBox="0 0 24 24"
                fill="#F59E0B"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
              </svg>
            </div>

            {/* Eyebrow */}
            <p className="text-[10px] tracking-[0.2em] text-[#F59E0B] uppercase mt-4">
              CERTIFICATE OF COMPLETION
            </p>

            {/* Title */}
            <h2 className="font-[var(--font-syne)] font-extrabold text-[28px] gradient-text mt-3">
              Learning Pathway Complete
            </h2>

            {/* Subtitle */}
            <p className="text-[var(--text-secondary)] text-sm mt-2 leading-relaxed">
              You have successfully completed all recommended courses for your target role
            </p>

            {/* Stats row */}
            <div className="bg-[rgba(79,158,248,0.05)] rounded-xl p-4 mt-6 grid grid-cols-3 gap-4">
              <div>
                <p className="font-[var(--font-syne)] font-extrabold text-2xl text-[#4F9EF8]">
                  {data.pathway.pathway.length}
                </p>
                <p className="text-[var(--text-muted)] text-xs mt-1">Courses Completed</p>
              </div>
              <div>
                <p className="font-[var(--font-syne)] font-extrabold text-2xl text-[#4F9EF8]">
                  {data.pathway.total_estimated_hours}h
                </p>
                <p className="text-[var(--text-muted)] text-xs mt-1">Hours of Learning</p>
              </div>
              <div>
                <p className="font-[var(--font-syne)] font-extrabold text-2xl text-[#4F9EF8]">
                  {Math.round(data.match_score * 100)}%
                </p>
                <p className="text-[var(--text-muted)] text-xs mt-1">Role Match Score</p>
              </div>
            </div>

            {/* Name line */}
            <p className="text-[var(--text-muted)] text-xs mt-4 pb-4 border-b border-[rgba(255,255,255,0.06)]">
              Prepared by AI-Adaptive Onboarding Engine
            </p>

            {/* Buttons */}
            <div className="flex gap-3 mt-6">
              <button
                onClick={handleDownloadCertificate}
                className="flex-1 h-11 bg-gradient-to-r from-[#4F9EF8] to-[#7C3AED] hover:from-[#4F9EF8]/90 hover:to-[#7C3AED]/90 text-white text-sm font-[var(--font-syne)] font-bold rounded-xl flex items-center justify-center gap-2 transition-all"
              >
                <Download size={16} /> Download Certificate
              </button>
              <button
                onClick={handleShareAchievement}
                className="flex-1 h-11 card-premium text-sm font-[var(--font-syne)] font-bold rounded-xl flex items-center justify-center gap-2 hover:border-[#4F9EF8]/30 transition-all"
              >
                <Share2 size={16} /> Share Achievement
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="max-w-6xl mx-auto px-6 py-4 border-t border-[rgba(255,255,255,0.04)] mt-12 flex items-center justify-between no-print">
        <p className="text-[11px] text-[var(--text-muted)]">
          AI-Adaptive Onboarding Engine — ARTPARK CodeForge Hackathon
        </p>
        <div className="flex items-center gap-3">
          {[
            "FastAPI",
            "Next.js",
            "OpenRouter",
            "Supabase",
            "NetworkX",
          ].map((tech) => (
            <span key={tech}
              className="text-[10px] text-[var(--text-muted)] bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.06)] px-2 py-0.5 rounded-[4px]">
              {tech}
            </span>
          ))}
        </div>
      </div>

      {/* Keyboard Shortcuts Bar */}
      <div className="fixed bottom-0 left-0 right-0 z-30 border-t border-[rgba(255,255,255,0.04)] bg-[rgba(6,8,16,0.9)] backdrop-blur-xl px-6 py-2 no-print">
        <div className="max-w-6xl mx-auto flex items-center justify-center gap-6">
          {[
            { key: "E", action: "Export" },
            { key: "C", action: "Copy" },
            { key: "H", action: "History" },
            { key: "R", action: "Reasoning" },
            { key: "Esc", action: "Go home" },
          ].map((s) => (
            <span key={s.key} className="flex items-center gap-1.5 text-[11px] text-[var(--text-muted)]">
              <kbd className="bg-[rgba(255,255,255,0.06)] border border-[rgba(255,255,255,0.1)] rounded-[4px] px-1.5 py-0.5 text-[10px] text-[var(--text-secondary)] font-mono">
                {s.key}
              </kbd>
              {s.action}
            </span>
          ))}
        </div>
      </div>

      <style dangerouslySetInnerHTML={{__html: `
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        @keyframes fade-in {
          0% { opacity: 0; transform: translateY(-10px); }
          100% { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.5s ease-out forwards;
        }
        .delay-300 { animation-delay: 300ms; }
        .fill-mode-forwards { animation-fill-mode: forwards; }
        @keyframes slide-in-right {
          0% { transform: translateX(100%); opacity: 0; }
          100% { transform: translateX(0); opacity: 1; }
        }
        .animate-slide-in-right {
          animation: slide-in-right 0.3s ease-out forwards;
        }
      `}} />
    </div>
  );
}

export default function Page() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#0A0F1E]" />}>
      <RoadmapContent />
    </Suspense>
  );
}
